 name: NeoSAPIAddons
 api-version: 1.14
 version: 1.0
 description: Various commands and skills that SkillAPI is too bad to do by itself
 author: Neoblade298
 depend: [SkillAPI]
 softdepend: [MythicMobs]
 main: me.neoblade298.neosapiaddons.Main
 commands: 
  neosapiaddons:
    description: Base command for usage
    usage: /neosapiaddons [command] [player] [arg]