 name: NeoConsumables
 version: 1.2
 api-version: 1.16
 description: Written originally by bananapuncher714, edited by Neoblade298
 depend: [SkillAPI, NeoCore]
 author: Neoblade298
 main: me.Neoblade298.NeoConsumables.Consumables
 commands:
   cons:
     description: Does its job
     usage: /cons