name: NeoBossRelics
main: me.neoblade298.neobossrelics.NeoBossRelics
author: [Neoblade298]
depend: [SkillAPI]
version: 1.0
api-version: 1.16
commands:
   relic:
      description: Various debug commands
      usage: /relic